github: remove fuzz coverage report generation
The stage fails with error [1]. Need to investigate what is the new
proper way of generating fuzz's coverage report.

[1]

Run /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-cov show target/x86_64-unknown-linux-gnu/release/arrayvec --format html --instr-profile=fuzz/coverage/arrayvec/coverage.profdata --Xdemangler=rustfilt > arrayvec.fuzz.coverage.html
error: Failed to load coverage: 'target/x86_64-unknown-linux-gnu/release/arrayvec': No coverage data found

Error: Process completed with exit code 1.